#Requires -Module @{ ModuleName = 'InvokeBuild'; ModuleVersion = '5.11.0' }

[CmdletBinding()]
param()

Set-StrictMode -Version Latest

$script:ModuleName = 'PSModuleGraph'
$script:SrcRoot = Join-Path (Join-Path $BuildRoot 'src') $ModuleName
$script:OutRoot = Join-Path (Join-Path $BuildRoot 'output') $ModuleName
$script:ManifestPath = Join-Path $SrcRoot "$ModuleName.psd1"
$script:TestsRoot = Join-Path $BuildRoot 'tests'
$script:AnalyzerSettings = Join-Path $BuildRoot 'PSScriptAnalyzerSettings.psd1'

task Clean {
    if (Test-Path -LiteralPath (Join-Path $BuildRoot 'output')) {
        Remove-Item -LiteralPath (Join-Path $BuildRoot 'output') -Recurse -Force
    }
}

task Lint {
    # Rule configuration lives in PSScriptAnalyzerSettings.psd1 so editors and
    # CI lint identically to this task.
    $results = @(Invoke-ScriptAnalyzer -Path $SrcRoot -Recurse -Settings $AnalyzerSettings)
    if ($results) {
        $results | Format-Table -AutoSize | Out-String | Write-Host
        throw "PSScriptAnalyzer reported $($results.Count) issue(s)."
    }
}

task Build Clean, {
    New-Item -ItemType Directory -Path $OutRoot -Force | Out-Null

    # Copy manifest
    Copy-Item -LiteralPath $ManifestPath -Destination (Join-Path $OutRoot "$ModuleName.psd1") -Force

    # Compose psm1 from private + public functions
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('# Auto-generated by PSModuleGraph.build.ps1 — do not edit.')
    [void]$sb.AppendLine('Set-StrictMode -Version Latest')
    [void]$sb.AppendLine()

    $privateDir = Join-Path $SrcRoot 'Private'
    if (Test-Path -LiteralPath $privateDir) {
        Get-ChildItem -Path $privateDir -Filter *.ps1 -File | Sort-Object Name | ForEach-Object {
            [void]$sb.AppendLine("# region $($_.Name)")
            [void]$sb.AppendLine((Get-Content -LiteralPath $_.FullName -Raw))
            [void]$sb.AppendLine("# endregion")
            [void]$sb.AppendLine()
        }
    }

    $publicDir = Join-Path $SrcRoot 'Public'
    $publicNames = @()
    if (Test-Path -LiteralPath $publicDir) {
        Get-ChildItem -Path $publicDir -Filter *.ps1 -File | Sort-Object Name | ForEach-Object {
            $publicNames += [System.IO.Path]::GetFileNameWithoutExtension($_.Name)
            [void]$sb.AppendLine("# region $($_.Name)")
            [void]$sb.AppendLine((Get-Content -LiteralPath $_.FullName -Raw))
            [void]$sb.AppendLine("# endregion")
            [void]$sb.AppendLine()
        }
    }

    if ($publicNames.Count -gt 0) {
        $exportList = ($publicNames | ForEach-Object { "'$_'" }) -join ', '
        [void]$sb.AppendLine("Export-ModuleMember -Function @($exportList)")
    }

    $outPsm1 = Join-Path $OutRoot "$ModuleName.psm1"
    [System.IO.File]::WriteAllText($outPsm1, $sb.ToString())

    # Copy any other root files (formats, types, etc.)
    Get-ChildItem -Path $SrcRoot -File | Where-Object {
        $_.Extension -notin @('.psd1', '.psm1') -and $_.Name -ne '.gitkeep'
    } | ForEach-Object {
        Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $OutRoot $_.Name) -Force
    }

    # Copy culture directories (en-US, fr-FR, ...) so Get-Help finds about_ topics.
    Get-ChildItem -Path $SrcRoot -Directory |
        Where-Object { $_.Name -match '^[a-z]{2}(-[A-Za-z]{2,4})?$' } |
        ForEach-Object {
            Copy-Item -LiteralPath $_.FullName -Destination $OutRoot -Recurse -Force
            Write-Build Green "  help: $($_.Name)"
        }

    Write-Build Green "Built $ModuleName -> $OutRoot"
}

task Test Build, {
    $pesterModule = Get-Module -Name Pester -ListAvailable |
        Where-Object { $_.Version -ge [version]'6.0.0' -and $_.Version -lt [version]'7.0.0' } |
        Sort-Object Version -Descending |
        Select-Object -First 1

    if (-not $pesterModule) {
        throw 'Pester 6.x is required. Run ./build.ps1 -Bootstrap'
    }

    Import-Module -Name $pesterModule.Path -Force

    $outputParent = Join-Path $BuildRoot 'output'

    $config = New-PesterConfiguration
    $config.Run.Path = $TestsRoot
    # Throw, not Exit: Run.Exit makes Pester call exit, which can terminate the
    # host process running the build. Throw raises inside InvokeBuild, which
    # fails the task properly and lets the rest of the build react.
    $config.Run.Throw = $true
    $config.Run.PassThru = $true
    $config.Output.Verbosity = 'Detailed'

    # Classic 'Should -Be' throws, so the suite cannot drift back to v5 style.
    $config.Should.DisableV5 = $true

    $config.TestResult.Enabled = $true
    $config.TestResult.OutputPath = Join-Path $outputParent 'testResults.xml'
    $config.TestResult.OutputFormat = 'NUnitXml'

    # Cover the built module, which is what the tests actually import.
    # CoverageGutters was removed in Pester 6 - do not add it back.
    $config.CodeCoverage.Enabled = $true
    $config.CodeCoverage.Path = Join-Path $OutRoot "$ModuleName.psm1"
    $config.CodeCoverage.OutputFormat = 'JaCoCo'
    $config.CodeCoverage.OutputPath = Join-Path $outputParent 'coverage.xml'
    $config.CodeCoverage.CoveragePercentTarget = 75

    # Ensure built module is preferred on PSModulePath for tests that Import-Module by name
    $env:PSModulePath = $outputParent + [System.IO.Path]::PathSeparator + $env:PSModulePath

    $result = Invoke-Pester -Configuration $config

    $coverage = $result.CodeCoverage
    if ($coverage) {
        $percent = [math]::Round($coverage.CoveragePercent, 2)
        $target = $coverage.CoveragePercentTarget
        Write-Build Green "Line coverage: $percent% (target $target%)"
    }
}

task Import Build, {
    $manifest = Join-Path $OutRoot "$ModuleName.psd1"
    Import-Module -Name $manifest -Force -Verbose
}

task . Clean, Lint, Build, Test
