#Requires -Module @{ ModuleName = 'InvokeBuild'; ModuleVersion = '5.11.0' }

[CmdletBinding()]
param()

Set-StrictMode -Version Latest

$script:ModuleName = 'PSModuleGraph'
$script:SrcRoot = Join-Path (Join-Path $BuildRoot 'src') $ModuleName
$script:OutRoot = Join-Path (Join-Path $BuildRoot 'output') $ModuleName
$script:ManifestPath = Join-Path $SrcRoot "$ModuleName.psd1"
$script:TestsRoot = Join-Path $BuildRoot 'tests'
$script:AnalyzerSettings = Join-Path $BuildRoot 'PSScriptAnalyzerSettings.psd1'

task Clean {
    if (Test-Path -LiteralPath (Join-Path $BuildRoot 'output')) {
        Remove-Item -LiteralPath (Join-Path $BuildRoot 'output') -Recurse -Force
    }
}

task Lint {
    # Rule configuration lives in PSScriptAnalyzerSettings.psd1 so editors and
    # CI lint identically to this task.
    $results = @(Invoke-ScriptAnalyzer -Path $SrcRoot -Recurse -Settings $AnalyzerSettings)
    if ($results) {
        $results | Format-Table -AutoSize | Out-String | Write-Host
        throw "PSScriptAnalyzer reported $($results.Count) issue(s)."
    }
}

task Build Clean, {
    New-Item -ItemType Directory -Path $OutRoot -Force | Out-Null

    # Copy manifest
    Copy-Item -LiteralPath $ManifestPath -Destination (Join-Path $OutRoot "$ModuleName.psd1") -Force

    # Compose psm1 from private + public functions
    $sb = [System.Text.StringBuilder]::new()
    [void]$sb.AppendLine('# Auto-generated by PSModuleGraph.build.ps1 — do not edit.')
    [void]$sb.AppendLine('Set-StrictMode -Version Latest')
    # Every source file is concatenated here at the module root, so $PSScriptRoot
    # differs from what the same code sees under the dev loader. Assets resolve
    # from $script:ModuleRoot in both. See Get-PSModuleGraphAsset.
    [void]$sb.AppendLine('$script:ModuleRoot = $PSScriptRoot')
    [void]$sb.AppendLine()

    $privateDir = Join-Path $SrcRoot 'Private'
    if (Test-Path -LiteralPath $privateDir) {
        # Recurse so Private/Html/*.ps1 is included. Sort by FullName, not Name,
        # so ordering is stable across subfolders.
        Get-ChildItem -Path $privateDir -Filter *.ps1 -File -Recurse | Sort-Object FullName | ForEach-Object {
            $relative = $_.FullName.Substring($privateDir.Length).TrimStart('\', '/')
            [void]$sb.AppendLine("# region $relative")
            [void]$sb.AppendLine((Get-Content -LiteralPath $_.FullName -Raw))
            [void]$sb.AppendLine("# endregion")
            [void]$sb.AppendLine()
        }
    }

    # Deliberately NOT recursive: the export list is derived from these
    # filenames, so Public/ must stay flat.
    $publicDir = Join-Path $SrcRoot 'Public'
    $publicNames = @()
    if (Test-Path -LiteralPath $publicDir) {
        Get-ChildItem -Path $publicDir -Filter *.ps1 -File | Sort-Object Name | ForEach-Object {
            $publicNames += [System.IO.Path]::GetFileNameWithoutExtension($_.Name)
            [void]$sb.AppendLine("# region $($_.Name)")
            [void]$sb.AppendLine((Get-Content -LiteralPath $_.FullName -Raw))
            [void]$sb.AppendLine("# endregion")
            [void]$sb.AppendLine()
        }
    }

    if ($publicNames.Count -gt 0) {
        $exportList = ($publicNames | ForEach-Object { "'$_'" }) -join ', '
        [void]$sb.AppendLine("Export-ModuleMember -Function @($exportList)")
    }

    $outPsm1 = Join-Path $OutRoot "$ModuleName.psm1"
    [System.IO.File]::WriteAllText($outPsm1, $sb.ToString())

    # Copy any other root files (formats, types, etc.)
    Get-ChildItem -Path $SrcRoot -File | Where-Object {
        $_.Extension -notin @('.psd1', '.psm1') -and $_.Name -ne '.gitkeep'
    } | ForEach-Object {
        Copy-Item -LiteralPath $_.FullName -Destination (Join-Path $OutRoot $_.Name) -Force
    }

    # Copy culture directories (en-US, fr-FR, ...) so Get-Help finds about_ topics.
    Get-ChildItem -Path $SrcRoot -Directory |
        Where-Object { $_.Name -match '^[a-z]{2}(-[A-Za-z]{2,4})?$' } |
        ForEach-Object {
            Copy-Item -LiteralPath $_.FullName -Destination $OutRoot -Recurse -Force
            Write-Build Green "  help: $($_.Name)"
        }

    Write-Build Green "Built $ModuleName -> $OutRoot"
}

task Dependencies {
    # PSGraphRender holds the HTML renderer and is a RequiredModules entry in
    # the manifest, so nothing here imports without it. It is not published, so
    # there is no Install-Module answer yet and the build has to find a checkout.
    #
    # Explicit and loud, in this order:
    #   1. $env:PSGRAPHRENDER_MODULE_PATH - a directory holding PSGraphRender/,
    #      for a checkout that is not a sibling or for CI.
    #   2. ../PSGraphRender/output - the sibling checkout, built.
    #
    # It throws rather than falling through to whatever is already on
    # PSModulePath. A build that passes because of what happened to be imported
    # in the session is a build that says nothing.
    $candidates = @()
    if ($env:PSGRAPHRENDER_MODULE_PATH) {
        $candidates += $env:PSGRAPHRENDER_MODULE_PATH
    }
    $sibling = Join-Path (Split-Path -Path $BuildRoot -Parent) 'PSGraphRender'
    $candidates += (Join-Path $sibling 'output')

    $resolved = $null
    foreach ($candidate in $candidates) {
        if (Test-Path -LiteralPath (Join-Path (Join-Path $candidate 'PSGraphRender') 'PSGraphRender.psd1')) {
            $resolved = (Resolve-Path -LiteralPath $candidate).ProviderPath
            break
        }
    }

    if (-not $resolved) {
        $hint = if (Test-Path -LiteralPath $sibling) {
            "Found '$sibling' but no built module inside it. Run ./build.ps1 there first."
        }
        else {
            "Expected a sibling checkout at '$sibling', or set `$env:PSGRAPHRENDER_MODULE_PATH to a directory containing PSGraphRender/."
        }
        throw "PSGraphRender could not be resolved. $hint"
    }

    # Finding a module is not the same as finding the right one. This step
    # reported success while checking nothing, and a resolution step that cannot
    # fail is the same defect as a workflow that never parsed: the sibling
    # checkout drifted three minor versions past the pin and the build went on
    # using it until a golden comparison broke somewhere unrelated.
    $renderer = Import-PowerShellDataFile -LiteralPath (Join-Path (Join-Path $resolved 'PSGraphRender') 'PSGraphRender.psd1')
    $found = [version]$renderer.ModuleVersion
    $declared = @(
        (Import-PowerShellDataFile -LiteralPath $ManifestPath).RequiredModules |
            Where-Object { $_ -is [System.Collections.IDictionary] -and $_['ModuleName'] -eq 'PSGraphRender' }
    )
    if ($declared.Count -ne 1) {
        throw ("PSModuleGraph.psd1 declares $($declared.Count) RequiredModules entries for PSGraphRender. " +
            'The version this build resolved cannot be checked against a requirement that is not there.')
    }
    $requirement = $declared[0]

    # Every constraint RequiredModules can express, not the one that happens to
    # be written today. A requirement that stops being checked when its shape
    # changes is a requirement nobody is checking.
    if ($requirement['RequiredVersion'] -and $found -ne [version]$requirement['RequiredVersion']) {
        throw ("PSGraphRender at '$resolved' is $found; PSModuleGraph.psd1 requires exactly " +
            "$($requirement['RequiredVersion']). Build the pinned version or point " +
            '$env:PSGRAPHRENDER_MODULE_PATH at it.')
    }
    if ($requirement['ModuleVersion'] -and $found -lt [version]$requirement['ModuleVersion']) {
        throw ("PSGraphRender at '$resolved' is $found; PSModuleGraph.psd1 requires at least " +
            "$($requirement['ModuleVersion']). Build the sibling checkout or point " +
            '$env:PSGRAPHRENDER_MODULE_PATH at a newer one.')
    }
    if ($requirement['MaximumVersion'] -and $found -gt [version]$requirement['MaximumVersion']) {
        throw ("PSGraphRender at '$resolved' is $found; PSModuleGraph.psd1 allows at most " +
            "$($requirement['MaximumVersion']).")
    }

    $env:PSModulePath = $resolved + [System.IO.Path]::PathSeparator + $env:PSModulePath

    # The version, out loud. Only a floor is declared today, so a renderer newer
    # than the recorded goldens satisfies this check and still changes what they
    # compare against - which is what happened. Naming the version puts it next
    # to the failure rather than three tasks away from it.
    Write-Build Green "  PSGraphRender: $found at $resolved"
}

task Test Build, Dependencies, {
    $pesterModule = Get-Module -Name Pester -ListAvailable |
        Where-Object { $_.Version -ge [version]'6.0.0' -and $_.Version -lt [version]'7.0.0' } |
        Sort-Object Version -Descending |
        Select-Object -First 1

    if (-not $pesterModule) {
        throw 'Pester 6.x is required. Run ./build.ps1 -Bootstrap'
    }

    Import-Module -Name $pesterModule.Path -Force

    $outputParent = Join-Path $BuildRoot 'output'

    $config = New-PesterConfiguration
    $config.Run.Path = $TestsRoot
    # Throw, not Exit: Run.Exit makes Pester call exit, which can terminate the
    # host process running the build. Throw raises inside InvokeBuild, which
    # fails the task properly and lets the rest of the build react.
    $config.Run.Throw = $true
    $config.Run.PassThru = $true
    $config.Output.Verbosity = 'Detailed'

    # Classic 'Should -Be' throws, so the suite cannot drift back to v5 style.
    $config.Should.DisableV5 = $true

    # PreTag tests are seals on a FINISHED iteration, not checks on work in
    # progress. The build should stay green while an iteration is half done;
    # the tag should not. ./build.ps1 -Task PreTag runs them.
    $config.Filter.ExcludeTag = 'PreTag'

    $config.TestResult.Enabled = $true
    $config.TestResult.OutputPath = Join-Path $outputParent 'testResults.xml'
    $config.TestResult.OutputFormat = 'NUnitXml'

    # Cover the built module, which is what the tests actually import.
    # CoverageGutters was removed in Pester 6 - do not add it back.
    $config.CodeCoverage.Enabled = $true
    $config.CodeCoverage.Path = Join-Path $OutRoot "$ModuleName.psm1"
    $config.CodeCoverage.OutputFormat = 'JaCoCo'
    $config.CodeCoverage.OutputPath = Join-Path $outputParent 'coverage.xml'
    $config.CodeCoverage.CoveragePercentTarget = 75

    # Ensure built module is preferred on PSModulePath for tests that Import-Module by name
    $env:PSModulePath = $outputParent + [System.IO.Path]::PathSeparator + $env:PSModulePath

    $result = Invoke-Pester -Configuration $config

    # CoveragePercentTarget only REPORTS. It has never once failed a run, and a
    # threshold nobody has seen fail is a threshold nobody knows works - this
    # sat at 74.88% against a target of 75 through three green builds. The
    # throw is the gate; the setting above is just the number it reads.
    $coverage = $result.CodeCoverage
    if ($coverage) {
        $percent = [math]::Round($coverage.CoveragePercent, 2)
        $target = $coverage.CoveragePercentTarget
        if ($percent -lt $target) {
            throw "Line coverage $percent% is below the target of $target%. Raise coverage, or lower the target deliberately and say so in the ledger."
        }
        Write-Build Green "Line coverage: $percent% (target $target%)"
    }
}

task PreTag Build, Dependencies, {
    # The gates that seal an iteration, run before `git tag -a` and not before
    # anything else. Deliberately a separate task rather than part of Test: a
    # half-finished iteration should still be able to run a green build, which
    # is most of what a build is for.
    $pesterModule = Get-Module -Name Pester -ListAvailable |
        Where-Object { $_.Version -ge [version]'6.0.0' -and $_.Version -lt [version]'7.0.0' } |
        Sort-Object Version -Descending |
        Select-Object -First 1

    if (-not $pesterModule) {
        throw 'Pester 6.x is required. Run ./build.ps1 -Bootstrap'
    }

    Import-Module -Name $pesterModule.Path -Force

    $config = New-PesterConfiguration
    $config.Run.Path = $TestsRoot
    $config.Run.Throw = $true
    $config.Output.Verbosity = 'Detailed'
    $config.Should.DisableV5 = $true
    $config.Filter.Tag = 'PreTag'

    $env:PSModulePath = (Join-Path $BuildRoot 'output') + [System.IO.Path]::PathSeparator + $env:PSModulePath

    Invoke-Pester -Configuration $config
    Write-Build Green 'Pre-tag gates passed. Safe to tag.'
}

task Knowledge Build, Dependencies, {
    # The answer to a stale store, and it lives in the repository. Before
    # v0.2.0 the generator was a scratch script, so the freshness test could
    # turn the build red with a fix nobody could run - which is the shape of
    # test people delete.
    #
    # Both populations, in a fixed order, with a fixed stamp. Generation is
    # reproducible so staleness can be detected by comparing trees rather than
    # by counting records, and a fixed stamp is what makes byte-comparison
    # possible at all.
    Import-Module -Name (Join-Path $OutRoot "$ModuleName.psd1") -Force

    $stamp = $env:PSMODULEGRAPH_KNOWLEDGE_STAMP
    if (-not $stamp) { $stamp = '2026-08-26' }
    $store = Join-Path $BuildRoot 'knowledge'

    foreach ($module in $SrcRoot, (Join-Path $TestsRoot 'fixtures/SampleModule')) {
        $summary = Update-KnowledgeStore -Path $module -StoreRoot $store -GeneratedAt $stamp -Confirm:$false
        Write-Build Green "  $($summary.ModuleName): $($summary.RecordsWritten) of $($summary.RecordsKept) record(s) rewritten, $($summary.RecordsPruned) pruned, $($summary.FacetsGraded) facet grade(s)"
    }

    # The second namespace, and the third population. Patterns are subjects as
    # of v0.17.0 - knowledge/NAMING.md, "What may have a URN" - and their
    # records are generated from the pattern log rather than written by hand.
    # After the module populations, because it removes and rewrites only
    # subjects/pattern/ and must not race the tree the loop above replaces.
    $patterns = Update-KnowledgePatternSubject -Path (Join-Path $BuildRoot 'knowledge/patterns') `
        -StoreRoot $store -GeneratedAt $stamp -Confirm:$false
    Write-Build Green "  patterns: $($patterns.RecordsWritten) of $($patterns.RecordsKept) record(s) rewritten from $($patterns.PatternsRead) file(s), $($patterns.RecordsPruned) pruned"
}

task Import Build, Dependencies, {
    $manifest = Join-Path $OutRoot "$ModuleName.psd1"
    Import-Module -Name $manifest -Force -Verbose
}

task . Clean, Lint, Build, Test
