function Export-CorpusSql {
    <#
    .SYNOPSIS
        Renders ingested records as an idempotent SQL load script.
    .DESCRIPTION
        A FILE, not a connection. This module never opens a socket, and that is
        deliberate: the whole load is decided and written out before anything is
        applied, so `psql -f` can be read, diffed and reviewed first, and the
        module needs no driver, no credentials and no network to be tested.
        Separating deciding from doing is the same rule the rest of this
        repository is built on.

        Every statement is ON CONFLICT DO UPDATE, so re-running a load is a
        refresh rather than a duplicate. The whole file is one transaction: a
        half-loaded corpus is worse than an empty one, because it looks loaded.

        Numeric surrogate keys are resolved in SQL rather than guessed here.
        turn_id is a BIGSERIAL the database assigns, so a tool_call finds its
        turn by (session_id, ordinal) in a sub-select. Assigning ids on this
        side would make the script valid exactly once.
    .PARAMETER Ledger
        From Import-CorpusLedger.
    .PARAMETER PatternSet
        From Import-CorpusPattern. Optional.
    .PARAMETER Transcript
        From Import-CorpusTranscript. Optional.
    .PARAMETER TrainingExample
        From Export-CorpusTrainingSet. Optional.
    .PARAMETER Recurrence
        From Measure-CorpusRecurrence. Optional.
    .PARAMETER Path
        Write here instead of to the pipeline.
    .OUTPUTS
        The script as a string, or a FileInfo when -Path is given.
    #>
    [CmdletBinding()]
    [OutputType([string], [System.IO.FileInfo])]
    param(
        [Parameter(Mandatory, Position = 0)]
        [ValidateNotNull()]
        $Ledger,

        [Parameter()] $PatternSet,
        [Parameter()] $Transcript,
        [Parameter()] [object[]] $TrainingExample,
        [Parameter()] [object[]] $Recurrence,
        [Parameter()] [string] $Path
    )

    $sql = [System.Text.StringBuilder]::new()
    function Add-Line { param([string] $Text) [void]$sql.AppendLine($Text) }

    Add-Line '-- Generated by Export-CorpusSql. Do not edit; regenerate.'
    Add-Line '-- Idempotent: every insert upserts, so a re-run refreshes rather than duplicates.'
    Add-Line 'BEGIN;'
    Add-Line ''

    $sources = @()
    foreach ($set in $Ledger, $PatternSet, $Transcript) {
        if ($set -and $set.Sources) { $sources += @($set.Sources) }
    }

    Add-Line '-- corpus_source ------------------------------------------------------'
    foreach ($source in $sources) {
        Add-Line ("INSERT INTO corpus_source (source_id, kind, path, sha256, bytes, redacted) VALUES ({0}, {1}, {2}, {3}, {4}, {5}) ON CONFLICT (source_id) DO UPDATE SET sha256 = EXCLUDED.sha256, bytes = EXCLUDED.bytes, ingested_at = now();" -f
            (ConvertTo-SqlLiteral $source.SourceId), (ConvertTo-SqlLiteral $source.Kind),
            (ConvertTo-SqlLiteral $source.Path), (ConvertTo-SqlLiteral $source.Sha256),
            [int64]$source.Bytes, (ConvertTo-SqlLiteral $source.Redacted))
    }
    Add-Line ''

    Add-Line '-- iteration ----------------------------------------------------------'
    foreach ($entry in $Ledger.Iterations) {
        Add-Line ("INSERT INTO iteration (iteration_id, source_id, tag, entry_date, title, prompt_intent, personas, body) VALUES ({0}, {1}, {2}, {3}, {4}, {5}, {6}, {7}) ON CONFLICT (iteration_id) DO UPDATE SET tag = EXCLUDED.tag, body = EXCLUDED.body;" -f
            (ConvertTo-SqlLiteral $entry.IterationId), (ConvertTo-SqlLiteral $entry.SourceId),
            (ConvertTo-SqlLiteral $entry.Tag), (ConvertTo-SqlLiteral $entry.EntryDate),
            (ConvertTo-SqlLiteral $entry.Title), (ConvertTo-SqlLiteral $entry.PromptIntent),
            (ConvertTo-SqlArray $entry.Personas), (ConvertTo-SqlLiteral $entry.Body))
    }
    Add-Line ''

    Add-Line '-- thread -------------------------------------------------------------'
    foreach ($thread in $Ledger.Threads) {
        Add-Line ("INSERT INTO thread (thread_id, opened_by, closed_by, carried_count, lifespan, state, body) VALUES ({0}, {1}, {2}, {3}, {4}, {5}, {6}) ON CONFLICT (thread_id) DO UPDATE SET closed_by = EXCLUDED.closed_by, carried_count = EXCLUDED.carried_count, lifespan = EXCLUDED.lifespan, state = EXCLUDED.state;" -f
            (ConvertTo-SqlLiteral $thread.ThreadId), (ConvertTo-SqlLiteral $thread.OpenedBy),
            (ConvertTo-SqlLiteral $thread.ClosedBy), [int]$thread.CarriedCount,
            (ConvertTo-SqlLiteral $thread.Lifespan), (ConvertTo-SqlLiteral $thread.State),
            (ConvertTo-SqlLiteral $thread.Body))
    }
    Add-Line ''

    Add-Line '-- claim --------------------------------------------------------------'
    # Deleted and rewritten rather than upserted: a claim has no natural key
    # beyond its position, and an edited entry that removes a bullet would
    # otherwise leave the removed claim in the table forever.
    Add-Line 'DELETE FROM claim;'
    foreach ($claim in $Ledger.Claims) {
        Add-Line ("INSERT INTO claim (iteration_id, section, ordinal, body, hedged) VALUES ({0}, {1}, {2}, {3}, {4});" -f
            (ConvertTo-SqlLiteral $claim.IterationId), (ConvertTo-SqlLiteral $claim.Section),
            [int]$claim.Ordinal, (ConvertTo-SqlLiteral $claim.Body), (ConvertTo-SqlLiteral $claim.Hedged))
    }
    Add-Line ''

    if ($PatternSet) {
        Add-Line '-- pattern ------------------------------------------------------------'
        foreach ($pattern in $PatternSet.Patterns) {
            Add-Line ("INSERT INTO pattern (pattern_id, iteration_id, tag, confidence, scales, statement, handoff) VALUES ({0}, {1}, {2}, {3}, {4}, {5}, {6}) ON CONFLICT (pattern_id) DO UPDATE SET confidence = EXCLUDED.confidence, statement = EXCLUDED.statement, handoff = EXCLUDED.handoff;" -f
                (ConvertTo-SqlLiteral $pattern.PatternId), (ConvertTo-SqlLiteral $pattern.IterationId),
                (ConvertTo-SqlLiteral $pattern.Tag), ([double]$pattern.Confidence).ToString([cultureinfo]::InvariantCulture),
                (ConvertTo-SqlArray $pattern.Scales), (ConvertTo-SqlLiteral $pattern.Statement),
                (ConvertTo-SqlLiteral $pattern.Handoff))
        }
        Add-Line ''
    }

    if ($Transcript) {
        Add-Line '-- session / turn / tool_call -----------------------------------------'
        foreach ($session in $Transcript.Sessions) {
            Add-Line ("INSERT INTO session (session_id, source_id, project, git_branch, started_at, ended_at, turn_count) VALUES ({0}, {1}, {2}, {3}, {4}, {5}, {6}) ON CONFLICT (session_id) DO UPDATE SET turn_count = EXCLUDED.turn_count, ended_at = EXCLUDED.ended_at;" -f
                (ConvertTo-SqlLiteral $session.SessionId), (ConvertTo-SqlLiteral $session.SourceId),
                (ConvertTo-SqlLiteral $session.Project), (ConvertTo-SqlLiteral $session.GitBranch),
                (ConvertTo-SqlLiteral $session.StartedAt), (ConvertTo-SqlLiteral $session.EndedAt),
                [int]$session.TurnCount)
        }
        foreach ($turn in $Transcript.Turns) {
            Add-Line ("INSERT INTO turn (session_id, ordinal, uuid, parent_uuid, role, model, text, thinking_chars, input_tokens, output_tokens, cache_read_tokens, at) VALUES ({0}, {1}, {2}, {3}, {4}, {5}, {6}, {7}, {8}, {9}, {10}, {11}) ON CONFLICT (session_id, ordinal) DO UPDATE SET text = EXCLUDED.text;" -f
                (ConvertTo-SqlLiteral $turn.SessionId), [int]$turn.Ordinal,
                (ConvertTo-SqlLiteral $turn.Uuid), (ConvertTo-SqlLiteral $turn.ParentUuid),
                (ConvertTo-SqlLiteral $turn.Role), (ConvertTo-SqlLiteral $turn.Model),
                (ConvertTo-SqlLiteral $turn.Text), [int]$turn.ThinkingChars,
                (ConvertTo-SqlLiteral $turn.InputTokens), (ConvertTo-SqlLiteral $turn.OutputTokens),
                (ConvertTo-SqlLiteral $turn.CacheReadTokens), (ConvertTo-SqlLiteral $turn.At))
        }
        Add-Line 'DELETE FROM tool_call;'
        foreach ($call in $Transcript.ToolCalls) {
            $session, $ordinal = $call.TurnKey -split '#'
            # The surrogate key is the database's to assign, so the turn is
            # found by its natural key here rather than guessed on this side.
            Add-Line ("INSERT INTO tool_call (turn_id, ordinal, tool_name, input_summary) SELECT turn_id, {0}, {1}, {2} FROM turn WHERE session_id = {3} AND ordinal = {4};" -f
                [int]$call.Ordinal, (ConvertTo-SqlLiteral $call.ToolName),
                (ConvertTo-SqlLiteral $call.InputSummary),
                (ConvertTo-SqlLiteral $session), [int]$ordinal)
        }
        Add-Line ''
    }

    if ($Recurrence) {
        Add-Line '-- term_recurrence ----------------------------------------------------'
        Add-Line 'DELETE FROM term_recurrence;'
        foreach ($row in $Recurrence) {
            Add-Line ("INSERT INTO term_recurrence (term, iterations, occurrences, first_seen, last_seen, example) VALUES ({0}, {1}, {2}, {3}, {4}, {5});" -f
                (ConvertTo-SqlLiteral $row.Term), [int]$row.Iterations, [int]$row.Occurrences,
                (ConvertTo-SqlLiteral $row.FirstSeen), (ConvertTo-SqlLiteral $row.LastSeen),
                (ConvertTo-SqlLiteral $row.Example))
        }
        Add-Line ''
    }

    if ($TrainingExample) {
        Add-Line '-- training_example ---------------------------------------------------'
        Add-Line 'DELETE FROM training_example;'
        foreach ($example in $TrainingExample) {
            Add-Line ("INSERT INTO training_example (kind, prompt, completion, weight, metadata) VALUES ({0}, {1}, {2}, {3}, {4}::jsonb);" -f
                (ConvertTo-SqlLiteral $example.Kind), (ConvertTo-SqlLiteral $example.Prompt),
                (ConvertTo-SqlLiteral $example.Completion),
                ([double]$example.Weight).ToString([cultureinfo]::InvariantCulture),
                (ConvertTo-SqlLiteral ($example.Metadata | ConvertTo-Json -Depth 6 -Compress)))
        }
        Add-Line ''
    }

    Add-Line 'COMMIT;'

    $text = $sql.ToString()
    if ($Path) {
        $directory = Split-Path -Path $Path -Parent
        if ($directory -and -not (Test-Path -LiteralPath $directory)) {
            [System.IO.Directory]::CreateDirectory($directory) | Out-Null
        }
        # UTF-8 without a BOM. psql reads the file as bytes and a BOM ahead of
        # the first statement is a syntax error.
        [System.IO.File]::WriteAllText($Path, $text, [System.Text.UTF8Encoding]::new($false))
        return Get-Item -LiteralPath $Path
    }
    $text
}
